export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILED = 'FETCH_MOVIES_FAILED';
export const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS';
export const DELETE_MOVIE_FAILED = 'DELETE_MOVIE_FAILED';
export const ADD_MOVIE_SUCCESS = 'ADD_MOVIE_SUCCESS';
export const ADD_MOVIE_FAILED = 'ADD_MOVIE_FAILED';
export const EDIT_MOVIE_SUCCESS = 'EDIT_MOVIE_SUCCESS';
export const EDIT_MOVIE_FAILED = 'EDIT_MOVIE_FAILED';
export const SET_FILTERED_MOVIES = 'SET_FILTERED_MOVIES';
export const SET_SORTED_MOVIES = 'SET_SORTED_MOVIES';
export const SET_MODAL = 'SET_MODAL';
export const SET_MOVIE_OPENED = 'SET_MOVIE_OPENED';

export const SET_ACTIVE_FILTER = 'SET_ACTIVE_FILTER';
export const SET_SORT_TYPE = 'SET_SORT_TYPE';
